# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfbc7d2ac279476f1569cdea077925c2ec882a6141b358c005d36dc8f7718e2c39ab713a61685b4ccc1ba0d836250ca028399e6182cc52924d0770bbf85a09d2

test:
  secret_key_base: 7a59ba46fa91c0b9183e657d0511fc4ae6e71b2cf2e40ae6caf13998e2a4edb10d756c6be6e0f531b346989c6d391815e8b556a463f9ae1c1285b15fe552e2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
